title: Varun Srinivasan
author:
  name: Varun Srinivasan

  picture:
    path: /assets/me.png
description: #> # this means to ignore newlines until "baseurl:"
  Environmental Engineer, Microbial Resource Manager, Bioinformatics-Enthusiast, R-Nerd, Amateur Chef and DIY-Lover!

url: "https://vnsriniv.github.io"
baseurl: /
#twitter_username: vnsriniv
#github_username:  vnsriniv
#linkedin: Varun Srinivasan
#title_image: https://pbs.twimg.com/media/Dgd2h1NVAAA80QZ.jpg

google_analytics: UA-121787867-1

# Build settings
markdown: kramdown
#theme: minima
remote_theme: qwtel/hydejack@gem-7.5.1
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-remote-theme

accent_image: /assets/bg.png
logo: /assets/me.png
#Pages in header order
#header-pages:
#  - 1-research.md
#  - 2-publications.md
#  - 3-teaching.md
#  - 4-blog.md
#  - 5-about.md

#Sidebar links
defaults:
  - scope:
      path: 1-research.md
    values:
      menu: true
      order: 1
  - scope:
      path: 2-publications.md
    values:
      menu: true
      order: 2
  - scope:
      path: 3-teaching.md
    values:
      menu: true
      order: 3
  - scope:
      path: 4-blog.md
    values:
      menu: true
      order: 4
  - scope:
        path: 5-about.md
    values:
      menu: true
      order: 5
